import { Poppins, Alfa_Slab_One } from "next/font/google";
import "./globals.css";
import Header from './Header/Header';
import Footer from './Footer/Footer';

import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

const poppins = Poppins({
  weight: '400',
  subsets: ["latin"],
});

const alfaSlabOne = Alfa_Slab_One({
  weight: '400',
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <div className="layout-container">
          <Header />
          <main className="content-container">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
   
  );
}

